
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: iclone_development

  
test:
  <<: *default
  database: iclone_test


production:
  <<: *default
  database: iclone_production
  username: iclone
  password: <%= ENV['ICLONE_DATABASE_PASSWORD'] %>
